#!/bin/bash
# InsightAgent Deployment Script
# Backend: Cloud Run | Frontend: Firebase Hosting

set -e

# Configuration
PROJECT_ID="insightagent-adk"
FIREBASE_PROJECT_ID="insightagent-adk-8b283"
REGION="asia-south1"
ARTIFACT_REGISTRY="asia-south1-docker.pkg.dev/${PROJECT_ID}/insightagent"

# Service names
BACKEND_SERVICE="insightagent"
FIREBASE_SITE="insightagent-app"

# URLs
FRONTEND_URL="https://insightagent-app.web.app"
BACKEND_URL="https://insightagent-650676557784.asia-south1.run.app"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

print_status() {
    echo -e "${GREEN}[INFO]${NC} $1" >&2
}

print_warning() {
    echo -e "${YELLOW}[WARN]${NC} $1" >&2
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1" >&2
}

deploy_backend() {
    print_status "Deploying backend to Cloud Run..."

    cd "${PROJECT_ROOT}/backend"

    # Build and push image
    print_status "Building backend Docker image..."
    gcloud builds submit \
        --tag="${ARTIFACT_REGISTRY}/backend:latest" \
        --project="${PROJECT_ID}" \
        --region="${REGION}" >&2

    # Deploy to Cloud Run
    print_status "Deploying to Cloud Run..."
    gcloud run deploy "${BACKEND_SERVICE}" \
        --image="${ARTIFACT_REGISTRY}/backend:latest" \
        --project="${PROJECT_ID}" \
        --region="${REGION}" \
        --allow-unauthenticated \
        --port=8080 \
        --memory=2Gi \
        --cpu=2 \
        --min-instances=0 \
        --max-instances=5 \
        --service-account="insightagent-sa@${PROJECT_ID}.iam.gserviceaccount.com" \
        --update-env-vars="GCP_PROJECT_ID=${PROJECT_ID},VERTEX_LOCATION=${REGION},ENVIRONMENT=production" >&2

    local url
    url=$(gcloud run services describe "${BACKEND_SERVICE}" \
        --project="${PROJECT_ID}" \
        --region="${REGION}" \
        --format="value(status.url)")

    print_status "Backend deployed: ${url}"
    echo "${url}"
}

deploy_frontend() {
    print_status "Deploying frontend to Firebase Hosting..."

    cd "${PROJECT_ROOT}/frontend"

    # Get API key from environment, Cloud Run, or backend .env (in that order)
    local api_key="${DEMO_API_KEY:-}"
    if [ -z "${api_key}" ]; then
        api_key=$(
            gcloud run services describe "${BACKEND_SERVICE}" \
                --project="${PROJECT_ID}" \
                --region="${REGION}" \
                --format="value(spec.template.spec.containers[0].env[?name='DEMO_API_KEY'].value)" 2>/dev/null || true
        )
    fi
    if [ -z "${api_key}" ] && [ -f "${PROJECT_ROOT}/backend/.env" ]; then
        print_warning "Falling back to ${PROJECT_ROOT}/backend/.env for DEMO_API_KEY (use DEMO_API_KEY env var for production deploys)."
        api_key=$(grep -E "^DEMO_API_KEY=" "${PROJECT_ROOT}/backend/.env" | cut -d'=' -f2 | tr -d '"' | tr -d "'")
    fi

    if [ -z "${api_key}" ]; then
        print_error "DEMO_API_KEY not found. Set it in backend/.env or as environment variable."
        return 1
    fi

    # Update .env.production with API key (not committed to git)
    print_status "Configuring production environment..."
    cat > .env.production << EOF
# InsightAgent Production Environment (auto-generated by deploy.sh)
VITE_API_KEY=${api_key}
VITE_API_BASE_URL=${BACKEND_URL}/api
EOF

    # Build production bundle
    print_status "Building frontend..."
    npm run build >&2

    # Deploy to Firebase Hosting
    print_status "Deploying to Firebase Hosting..."
    firebase deploy --only hosting --project="${FIREBASE_PROJECT_ID}" >&2

    print_status "Frontend deployed: ${FRONTEND_URL}"
    echo "${FRONTEND_URL}"
}

update_cors() {
    local frontend_url="$1"

    print_status "Updating backend CORS to allow: ${frontend_url}"

    gcloud run services update "${BACKEND_SERVICE}" \
        --project="${PROJECT_ID}" \
        --region="${REGION}" \
        --update-env-vars="ALLOWED_CORS_ORIGIN=${frontend_url}" >&2

    print_status "CORS updated"
}

warmup_backend() {
    local min_instances="${1:-1}"

    print_status "Setting backend min instances to ${min_instances}..."

    gcloud run services update "${BACKEND_SERVICE}" \
        --project="${PROJECT_ID}" \
        --region="${REGION}" \
        --min-instances="${min_instances}" >&2

    print_status "Backend min instances updated to ${min_instances}"
}

show_status() {
    print_status "Deployment status:"
    echo ""

    echo "Backend (Cloud Run):"
    gcloud run services describe "${BACKEND_SERVICE}" \
        --project="${PROJECT_ID}" \
        --region="${REGION}" \
        --format="table(status.url,status.conditions[0].status,spec.template.spec.containers[0].resources.limits.memory)" 2>/dev/null || echo "  Not deployed"

    echo ""
    echo "Frontend (Firebase Hosting):"
    echo "  URL: ${FRONTEND_URL}"
    echo "  Site: ${FIREBASE_SITE}"
    echo "  Project: ${FIREBASE_PROJECT_ID}"
}

usage() {
    cat << EOF
InsightAgent Deployment Script

Usage: $0 [command]

Commands:
  all         Deploy both backend and frontend (default)
  backend     Deploy backend to Cloud Run
  frontend    Deploy frontend to Firebase Hosting
  warmup      Set backend min-instances=1 (reduce cold starts)
  cooldown    Set backend min-instances=0 (save costs)
  status      Show deployment status

Examples:
  $0              # Deploy both services
  $0 backend      # Deploy only backend
  $0 frontend     # Deploy only frontend
  $0 warmup       # Warm up backend before demo
  $0 cooldown     # Cool down after demo

Production URLs:
  Frontend: ${FRONTEND_URL}
  Backend:  ${BACKEND_URL}

EOF
}

# Main
main() {
    local command="${1:-all}"

    case "${command}" in
        -h|--help)
            usage
            exit 0
            ;;
        all)
            print_status "Starting full deployment..."
            deploy_backend >/dev/null
            deploy_frontend >/dev/null
            print_status "Deployment complete!"
            echo ""
            echo "Frontend: ${FRONTEND_URL}"
            echo "Backend:  ${BACKEND_URL}"
            echo "API Docs: ${BACKEND_URL}/docs"
            ;;
        backend)
            deploy_backend
            ;;
        frontend)
            deploy_frontend
            ;;
        warmup)
            warmup_backend 1
            ;;
        cooldown)
            warmup_backend 0
            ;;
        status)
            show_status
            ;;
        *)
            print_error "Unknown command: ${command}"
            usage
            exit 1
            ;;
    esac
}

main "$@"
